name: Check Color Codes

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-color-codes:
    name: Check Color Codes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - run: ruby scripts/app.rb
